// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFG3917YJvcQjhiQZwtv_2vxHY7oXpfZs',
    appId: '1:303768360347:web:116d2dfdd6e6c19b537d3e',
    messagingSenderId: '303768360347',
    projectId: 'autoprint-7f97c',
    authDomain: 'autoprint-7f97c.firebaseapp.com',
    databaseURL: 'https://autoprint-7f97c-default-rtdb.firebaseio.com',
    storageBucket: 'autoprint-7f97c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8vsYa5gJOYU1skSz865aKjgE2C3T5qo',
    appId: '1:303768360347:android:ec875e81c19dc115537d3e',
    messagingSenderId: '303768360347',
    projectId: 'autoprint-7f97c',
    databaseURL: 'https://autoprint-7f97c-default-rtdb.firebaseio.com',
    storageBucket: 'autoprint-7f97c.firebasestorage.app',
  );
}
